### ISSUE TITLE
功能请求：将问题和回答添加到 Markdown 文件中

### ISSUE THREAD

**Issue by Burgess-Hu** [reorx/Share-to-ChatGPT-Shortcut#1]
你好，能否将每一次的问题和回答都按当前日期添加到 iCloud 快捷指令文件夹中的一个 Mrakdown 文件中，方便之后查阅，虽然已经直接复制到剪贴板了，但是有时候不小心会丢失，又得重新询问一次😂。

**Comment by reorx** [comment]
这个功能确实有必要存在，不过我希望做成是可配置的，默认不打开，因为一般用户只是想简单地得到结果，也不知道怎么在 iCloud 中打开 markdown

**Comment by Burgess-Hu** [comment]
可配置的话，我不太懂，不过将问题和结果写入 Markdown 应该不难，我上午研究了一下，快捷指令自带了一个「追加到文本文件」的操作，只需要先将输入的内容和日期先写入一个 Markdown，再将返回的结果后置到该文件即可，不过返回的结果要用正则表达式提取一下，去掉空行什么的。

**Comment by reorx** [comment]
最新的版本里增加了 history-file 配置，只有当其有值的时候才会把问题和结果记录到这个文件中

**Comment by Burgess-Hu** [comment]
好的，感谢！
