### ISSUE TITLE
能否增加一个温度系数设置

### ISSUE THREAD

**Issue by Joseph2Geek** [reorx/Share-to-ChatGPT-Shortcut#2]
考虑到翻译追求的准确度 有时候需要调整温度系数 能把这个设定也加入进去吗 谢谢大佬

**Comment by reorx** [comment]
暂时没有想到足够好的办法来做这个事情。翻译只是 prompt 之一，prompts 和其对应的名称保存在一个字典中：
<img width="623" alt="image" src="https://github.com/reorx/Share-to-ChatGPT-Shortcut/assets/405972/fecb1101-53b2-4872-818c-ea571675ba7b">

在这个字典中，很难使用嵌套的方式定义数值，因此每个 prompt 无法单独调节 temperature, presence penalty 等参数。但如果允许参数全局调整，又会对所有 prompt 产生影响。

**Comment by Joseph2Geek** [comment]
不知道每个prompt单独把温度系数写在文本里面有没有用- - 主要是我测试了同样的prompt用yetone的openai translator的翻译结果明显要更好 它那个温度系数应该调到0了 每次输出结果是固定的....

**Comment by reorx** [comment]
嗯，这个在逻辑上确实不是很难的需求，但放在 Shortcuts 里想要实现得通用却非常麻烦，涉及到逻辑判断的事情 Shortcuts 还是无法与真正的编程语言相比。

你可以复制一个新的 Shortcut，专门用于翻译，把参数添加到下图所示的地方：
<img width="1312" alt="image" src="https://github.com/reorx/Share-to-ChatGPT-Shortcut/assets/405972/ad982294-c19d-417c-b079-220a57ddf65c">

**Comment by Joseph2Geek** [comment]
好的，我来试试，感谢！

**Comment by Joseph2Geek** [comment]
已经设置好了，谢谢大佬，不得不说快捷指令这种系统级调用还是太方便了，比app和浏览器扩展都要好用，小小建议如果那个纯聊天chat可以加入whisper API调用语音就更好了，我现在实现方法是单独弄了个shortcut.....然后背面连按三下呼出“whisper” 语音输入自动复制到剪贴板 再连按两下呼出“share to ChatGPT” 贴进去.....

**Comment by reorx** [comment]
你是希望通过语音的方式来调用 ChatGPT 吗？那可以试试专门做这件事情的 Shortcut https://github.com/Yue-Yang/ChatGPT-Siri

**Comment by Joseph2Geek** [comment]
我看了这个用的是Siri 但是Siri不支持多语言混合识别而openai的whisper可以做到而且识别更精准 具体可以看看官方ios客户端那个语音输入 识别率相当精准....

**Comment by reorx** [comment]
明白了，感谢指点！如果有空我会尝试下单独做一个用 Whisper API 驱动的聊天式 Shortcut
